# SPDX-FileCopyrightText: Night Theme Switcher Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

extends:
  - ./lint/eslintrc-gjs.yml
  - ./lint/eslintrc-shell.yml
  - ./lint/eslintrc-extension.yml
