# SPDX-FileCopyrightText: 2020, 2021 Romain Vigier <contact AT romainvigier.fr>
# SPDX-License-Identifier: GPL-3.0-or-later

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - test
  - build

test:
  stage: test
  image: node:latest
  rules:
    - changes:
      - src/**/*
      - tests/**/*
  cache:
    paths:
      - node_modules
  script:
    - make deps-install
    - make test

build:
  stage: build
  image: registry.gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension:latest
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - make build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expose_as: "extension"
    paths:
      - build/nightthemeswitcher@romainvigier.fr.shell-extension.zip
