# Night Theme Switcher Gnome Shell extension
#
# Copyright (C) 2020 Romain Vigier
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http s ://www.gnu.org/licenses/>.


image: fedora:latest

cache:
  paths:
    - .dnf_cache
    - node_modules

stages:
  - test
  - build

before_script:
  - mkdir -p .dnf_cache
  - dnf --setopt=cachedir=$(pwd)/.dnf_cache --setopt=keepcache=True update -y
  - dnf --setopt=cachedir=$(pwd)/.dnf_cache --setopt=keepcache=True install -y make

test:
  stage: test
  rules:
    changes:
      - src/
  script:
    - dnf --setopt=cachedir=$(pwd)/.dnf_cache --setopt=keepcache=True install -y node npm
    - make deps-install
    - make test

build:
  stage: build
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - if: '$CI_COMMIT_TAG'
  script:
    - dnf --setopt=cachedir=$(pwd)/.dnf_cache --setopt=keepcache=True install -y gnome-shell gettext
    - make build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expose_as: "extension"
    paths:
      - build/nightthemeswitcher@romainvigier.fr.shell-extension.zip
